name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Prepare upload dir
        run: |
          rsync -av --exclude 'node_modules' --exclude '.env' --exclude 'storage' --exclude 'logs' ./ ./deploy_tmp

      - name: Upload files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy_tmp/*"
          target: "/var/www/html/portfolio-site-backend-adonis"
          rm: false
          overwrite: true


      - name: Install dependencies and restart app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/portfolio-site-backend-adonis
            npm install --production
            pm2 startOrRestart pm2.config.json
