name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Deploy with rsync
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rsync -avz --delete \
            --exclude 'node_modules' \
            --exclude '.env' \
            --exclude 'storage' \
            --exclude 'logs' \
            -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" \
            ./ ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:/var/www/html/portfolio-site-backend-adonis

      - name: Install dependencies and build/start app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DB_HOST,DB_USER,DB_DATABASE,DB_PORT,APP_KEY,HOST,PORT,LOG_LEVEL
          script: |
            cd /var/www/html/portfolio-site-backend-adonis
            export DB_HOST="${DB_HOST}"
            export DB_USER="${DB_USER}"
            export DB_DATABASE="${DB_DATABASE}"
            export DB_PORT="${DB_PORT}"
            export APP_KEY="${APP_KEY}"
            export HOST="${HOST}"
            export PORT="${PORT}"
            export LOG_LEVEL="${LOG_LEVEL}"
            npm ci
            npm run build
            pm2 startOrRestart pm2.config.json --env production --update-env
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_PORT: ${{ secrets.DB_PORT }}
          APP_KEY: ${{ secrets.APP_KEY }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}